
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=datn;encrypt=true;trustservercertificate=true
#spring.datasource.username=root
#spring.datasource.password=123456789
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.show-sql=true
#spring.jpa.hibernate.ddl-auto=none
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/duantn
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true

custom-config:
  security:
    jwtSecret: jf9i4jgu83nfl0jfu57ejf7shdvffhdsvfsdvdshfhsdfvsdhfjf9i4jgu83nfl0jfu57ejf7shdvffhdsvfsdvdshfhsdfvsdhf
    jwtExpiration: 604800000

    endpointAuthorizations:
#      - { urlPattern: "/product", method: "POST", roles: ["ADMIN", "EMPLOYEE"] }
      - { urlPattern: "/bill", method: "POST", roles: ["ADMIN"] }

    unprotectedEndpoints:
      - { urlPattern: "/api/auth/login" }
      - { urlPattern: "/api/auth/register", method: "POST" }
      - { urlPattern: "/product", method: "GET" }
      - { urlPattern: "/product/**" }

server:
  port: 8080




